# Generated by Django 5.0.6 on 2024-08-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_delete_adminprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
