# Generated by Django 5.0.6 on 2024-08-31 21:27

from django.db import migrations
from django.utils.text import slugify
import uuid

def generate_unique_slugs(apps, schema_editor):
    User = apps.get_model('user', 'User')
    for user in User.objects.all():
        if not user.slug:  # Only generate if the slug is not already set
            base_slug = slugify(user.username) or str(uuid.uuid4())
            unique_slug = base_slug
            counter = 1
            while User.objects.filter(slug=unique_slug).exists():
                unique_slug = f"{base_slug}-{counter}"
                counter += 1
            user.slug = unique_slug
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_slug')
    ]

    operations = [
        migrations.RunPython(generate_unique_slugs),
    ]
