# Generated by Django 5.0.6 on 2024-08-31 21:32

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_generate_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]

