# Generated by Django 5.0.6 on 2024-09-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_make_slug_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
