# Generated by Django 5.0.6 on 2024-10-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_alter_user_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_new_user",
            field=models.BooleanField(default=True),
        ),
    ]
