# Generated by Django 5.0.6 on 2024-12-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_alter_user_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="slug",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("ORGANIZATION_FACULTY", "Organization Faculty"),
                    ("FACILITY_FACULTY", "Facility Faculty"),
                    ("FACULTY", "Faculty"),
                    ("LEADER", "Leader"),
                    ("ATTENDEE", "Attendee"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
